#!/Users/james/Documents/virtualenvs/codenode/bin/python
import os
os.environ['DJANGO_SETTINGS_MODULE'] = 'codenode.frontend._desktop_settings'


from django.core import management

if __name__ == "__main__":
    management.execute_from_command_line()


