#!/usr/bin/env bash

echo 'Deprecated.  Please use "codenode-admin resetdb"'
export PYTHONPATH=$PWD/..
rm env/data/codenode.db
cd env
django-admin.py syncdb --pythonpath=$PWD --settings="frontend.settings"
